# Generated by Django 6.0.6 on 2026-07-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('motif', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('observations_generales', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patient', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('personne_contact', models.CharField(max_length=100)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_diagnostic', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='saint_joseph.consultation')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
                'ordering': ['-date_diagnostic'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='saint_joseph.dossiermedical'),
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_formulaire', models.CharField(choices=[('ordonnance', 'Ordonnance'), ('certificat', 'Certificat'), ('analyse', 'Analyse'), ('hospitalisation', 'Hospitalisation'), ('conge', 'Congé'), ('autre', 'Autre')], max_length=50)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('finalise', 'Finalisé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
                ('motif_archivage', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='saint_joseph.consultation')),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='saint_joseph.patient'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='saint_joseph.consultation')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('motif', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_attente', 'En attente'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='saint_joseph.patient')),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_prevus', to='saint_joseph.utilisateur')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_heure'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profil', to='saint_joseph.utilisateur'),
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('lit', models.CharField(max_length=50)),
                ('chambre', models.CharField(blank=True, max_length=50, null=True)),
                ('etage', models.CharField(blank=True, max_length=50, null=True)),
                ('motif_admission', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('admission', 'Admission'), ('hospitalisee', 'Hospitalisée'), ('sortie', 'Sortie'), ('transfert', 'Transfert')], default='admission', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='saint_joseph.patient')),
                ('medecin_responsable', models.ForeignKey(limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_supervisees', to='saint_joseph.utilisateur')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
                'ordering': ['-date_admission'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_effectuees', to='saint_joseph.utilisateur'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('motif_archivage', models.TextField()),
                ('formulaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='saint_joseph.formulaire')),
                ('archiviste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_creees', to='saint_joseph.utilisateur')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
    ]
