# Generated by Django 6.0.6 on 2026-07-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint_joseph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='formulaire',
        ),
        migrations.AddField(
            model_name='archive',
            name='dossier_medical',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='saint_joseph.dossiermedical'),
            preserve_default=False,
        ),
    ]
