# Generated by Django 6.0.6 on 2026-07-28 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint_joseph', '0002_remove_archive_formulaire_archive_dossier_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='dossier_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='saint_joseph.dossiermedical'),
        ),
    ]
